# vim: set ft=ansible:

- name: Create Consul Template Config Directory
  file: name="{{ _consul_template.config_dir }}" state=directory owner="{{ _consul_template.user|default("root") }}" group="root" mode="0755"

- name: Create Consul Template Configuration Files ... Main
  template: src="etc/consul-template.d/{{ item }}.j2" dest="{{ _consul_template.config_dir }}/{{ item }}" owner="root" group="{{ _consul_template.group|default("root") }}" mode="0640"
  with_items:
    - "consul-template.cfg"

- name: Create Consul Template Configuration Files ... Template Definitions
  template: src="etc/consul-template.d/template.cfg.j2" dest="{{ _consul_template.config_dir }}/{{ item.key }}.cfg" owner="root" group="{{ _consul_template.group|default("root") }}" mode="0640"
  vars: { _template: "{{ item.value }}" }
  with_dict: "{{ _consul_template.templates }}"

